# Generated by Django 3.2 on 2022-05-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_house_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
