# Generated by Django 3.2 on 2022-06-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_default_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
