# Generated by Django 3.2 on 2022-05-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_hand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hand',
        ),
        migrations.AddField(
            model_name='product',
            name='has_hand',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
